# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Compliance check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: Setup node
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn test
        env:
          CI: true
