name: Test

on:
  - push
  - pull_request

jobs:
  rules_enforcing:
    name: "Rules enforcing"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        name: Setup node
        with:
          node-version: 10
      - run: yarn install
      - run: yarn test
        env:
          CI: true
